project_id = "sphublhnuetbuqaqgalo"

[functions.image-proxy]
verify_jwt = false

[functions.extract-receipt]
verify_jwt = false

[functions.scrape-product]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = false
